### PR TITLE
Execute signatures

### LINKED ISSUE #203: More convenient claim with safeExecutionSignatures usage
As soon as https://github.com/poanetwork/tokenbridge-contracts/issues/585 is implemented it makes sense to switch the OB UI to use this new functionality. It will allow users to re-send the claim transaction if by some reason the previous attempt failed due to the issue in the token contract (e.g. a token contract uses an AMM to perform some exchange but the slippage is not suitable).

### PR DESCRIPTION
**Pull request by alexkeating**
Closes #203

### CODE REVIEW

File: packages/react-app/src/hooks/useBridgeDirection.js [hunk 1]
```diff
@@ -15,8 +20,20 @@ export const useBridgeDirection = () => {
     ambLiveMonitorPrefix,
     homeGraphName,
     foreignGraphName,
+    foreignAmbAddress,
   } = bridgeConfig;
 
+  useMemo(
+    async version => {
+      await fetchAmbVersion(foreignAmbAddress, ethersProvider)
```
[the remark this answers is not in the document]
Comment (alexkeating) [reply packages/react-app/src/hooks/useBridgeDirection.js:28]: Good call!

File: packages/react-app/src/hooks/useBridgeDirection.js [hunk 2]
```diff
@@ -15,8 +20,22 @@ export const useBridgeDirection = () => {
...
+        .then(res => {
+          if (providerChainId === foreignChainId) {
```
Comment (dan13ram) [inline packages/react-app/src/hooks/useBridgeDirection.js:30]: @alexkeating 
Would it make more sense to reduce a network call and have this check before we call `fetchAmbVersion` ?

Currently this creates a network call every time `providerChainId` changes.
To reduce that we could use `getEthersProvider(foreignChainId)` from `lib/providers` instead of `ethersProvider` from `useWeb3Context`.

Comment (dan13ram) [reply packages/react-app/src/hooks/useBridgeDirection.js:30]: Also is this an incorrect usage of `useMemo`? Should it rather be `useEffect`?

Or we could have useMemo return the value. Something like:
```
const foreignAmbVersion = useMemo(async () => {});
```

Comment (dan13ram) [reply packages/react-app/src/hooks/useBridgeDirection.js:30]: Another thought I have is that will this network call be fired every time `useBridgeDirection` is used in all different places?

**Review by dan13ram — APPROVED** [review]
Great work!
